### ISSUE TITLE
Errors in original sentences :correct

### ISSUE THREAD

**Issue by BrettRey** [nert-nlp/cgel#46]
- sent_id = reviews-257296-0002 "superintendant" :correct "superintendent"
- sent_id = answers-20111108105400AASqPIh_ans-0007 "performance" :correct "perform"
- sent_id = reviews-106150-000 "and looks" :correct "and he looks"
- sent_id = reviews-275919-0010 missing period before"How". Should be two sentences.
- sent_id = reviews-275919-0010 missing "fast your" :correct "fast do your"
- sent_id = email-enronsent13_01-0092 "and the Para. 13" :correct "and Para. 13"
-

**Comment by nschneid** [comment]
So trying to correct grammatical errors gets dicey as there are often subjective calls and multiple ways to fix the problem. So far we've corrected misspellings and added a missing grammatical word that was necessary for the whole structure to work (missing 2nd "as" in comparative).

I suppose we could do a few more listed here, but I just want to point out that it can be a can of worms.

> * sent_id = reviews-257296-0002 "superintendant" :correct "superintendent"

already has `:correct` in the data

> * sent_id = reviews-275919-0010 missing period before"How". Should be two sentences.

fixed in 39fc24e

> * sent_id = answers-20111108105400AASqPIh_ans-0007 "performance" :correct "perform"

If we're correcting grammatical forms of words then "hospital" in this sentence should be "hospitals" as well right?

**Comment by BrettRey** [comment]
Yes, I missed _hospital_. I understand it's a can of worms, and I'm happy to recant.

**Comment by nschneid** [comment]
If correcting

* How fast your support queries get answered ?

should we also correct

* Billing takes 15 minutes and backoffice jobs takes 1 day's training

? They're consecutive sentences from the same document, so possibly the same author, though we can't be sure.

**Comment by BrettRey** [comment]
Yes
