### ISSUE TITLE
Improve evaluation

### ISSUE THREAD

**Issue by aryamanarora** [nert-nlp/cgel#65]
- How to evaluate GAPs?
- How to deal with substitution? May need to implement own Levenshtein algorithm
- Tokenisation (only discrepancy is merging?)

**Comment by nschneid** [comment]
Character offsets from original untokenized string to bypass tokenization differences! (Some of the CGEL trees have entire words that were accidentally omitted. Assuming the annotator has inserted no more than one word at any given point in the text, it could have a character span like 13,13. Should we actually score whether the word string matches given that edits to the word-string are possible e.g. misspellings, normalizing capitalization?)

**Comment by aryamanarora** [comment]
One nice thing about the character-level eval is that we can also double check the same underlying sentence is being parsed. Here's the performance of the UD->CGEL convertor on EWT and Twitter respectively:
```py
{'raw_dist': 5.92, 'normalised_dist': 0.06299538767574435, 'precision': 0.1690013046614213, 'recall': 0.1861626346918553, 'valid': 24, 'count': 100}
{'raw_dist': 4.984615384615385, 'normalised_dist': 0.09388778321396395, 'precision': 0.35429347629281677, 'recall': 0.3832528038475125, 'valid': 30, 'count': 65}
```

**Comment by nschneid** [comment]
Was going to bring up 3 more special cases in our meeting this week...until I realized we won't be meeting this week. :)

1. Inserted words: Our .cgel format allows for the annotator to specify that some words were missing from the original string due to a typo. I think such nodes can be assigned offsets in the same way as gaps (e.g., `_14` for an inserted word whose right sibling starts with original string character 14).
2. Gap coindexations: While the actual variables don't have to match, we want to make sure the coindexation is correct. Because every gap must have exactly one antecedent, an easy solution is to change its category to incorporate the offset of the antecedent (e.g. `GAP` becomes `GAP_10,13`). Then the labeled evaluation requires the antecedent to be in the correct position, and the unlabeled evaluation ignores it. (This does not check the category of the antecedent when scoring the gap, but of course the antecedent constituent is scored separately.)
3. Lexical strings: The tree can contain spelling corrections. Moreover, if two annotators insert a word in the same position, the word itself may or may not match (suppose a copula is missing and one annotator guesses "is" and the other "was"). Should the lexical strings be scored independently of their category (POS) and function?

**Comment by nschneid** [comment]
For the labeled score, I think counting a substitution as equal to an insertion plus a deletion is too harsh. Consider a gold Comp:PP constituent that is incorrectly predicted to have label Mod:PP. We're saying that error is *twice as bad* as if the constituent wasn't predicted at all! For computing precision and recall, counting it as .5 of an insertion and .5 of a deletion would make more sense I think.

This is a typical case BTW: when a constituent's span is correct, the function is usually more difficult to decide than the category.

**Comment by nschneid** [comment]
Yeah...what about .25 insertion & deletion costs if category XOR function is wrong, .5 if they're both wrong?

**Comment by nschneid** [comment]
Now implemented in `edit_distance()`: with `strict=False`, partial credit for aligned nodes:

- Nonterminals: 0.25 penalty for wrong function, 0.25 for wrong category (leave 0.5 credit for span)
- Lexical terminals: 0.25 penalty for wrong function, 0.25 for wrong category, 0.25 for wrong normalized string (leave 0.25 credit for token span)
- Gap terminals: 0.25 penalty for wrong function, 0.25 for wrong antecedent span (leave 0.5 credit for gap)

Thus, for every aligned node, 0 ≤ cost < 1. (This cost is divided equally between precision-error and recall-error.) As before, inserted/deleted nodes have a cost of 1.

Assignment of relative offsets to gaps and other inserted nodes still TBD.

**Comment by nschneid** [comment]
eval.py is now fully based on Tree Edit Distance, as documented in our [LAW 2023 paper](https://people.cs.georgetown.edu/nschneid/p/cgeltrees.pdf).
