### ISSUE TITLE
Aligning trees with different placement of $

### ISSUE THREAD

**Issue by aryamanarora** [nert-nlp/cgel#82]
Following decision in #73 it is not easy to score agreement on sentences with $. Should fix!

**Comment by nschneid** [comment]
It is as long as they pass validation right? Because they will both place the "$" after the number.

**Comment by nschneid** [comment]
The issue is that original annotations from before the reordering policy was instituted does not align with the final version in IAA50.

As a dirty hack, how about inserting in `_get_spans_rec()` before
https://github.com/nert-nlp/cgel/blob/f95ac8a87ac91d280e23afd68aac543ca093c7ed/cgel.py#L467

the special case:

```py
children = list(self.children[cur])
hasInvertedDetHead = False
lastDet = next((x for x,n in enumerate(children)[::-1] if n.deprel=='Det'), -1)
lastHead = next((x for x,n in enumerate(children)[::-1] if n.deprel=='Head'), 9999999)
if lastHead<lastDet:
    hasInvertedDetHead = True
    det = children.pop(lastDet)
    children.insert(lastHead, det)
    for i in children:
        add, add_string = self._get_spans_rec(i, offset)
        string += add_string
```

and in then in the existing loop add the guard:

```py
if not hasInvertedDetHead:
    string += add_string
```

This should reorder the currency symbol and its head constituent just for the purpose of constructing the string that will be used to check whether the sentences are aligned. The span offsets will continue to be mismatched, which correctly penalizes the reordering.

**Comment by nschneid** [comment]
This special cases is no longer necessary with TED-based evaluation
